constants:
  file:
    upload-directory: /home/download
  jwt:
    refresh-token-cookie-path: /otd-api/api/OTD/user/reissue

server:
  port: 8080

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"


spring:
  cloud:
    kubernetes:
      discovery:
        enabled: true
      reload:
        enabled: true
        strategy: refresh
  datasource:
    url: jdbc:log4jdbc:mariadb://192.168.0.93/hsb
    username: hsb
    password: green502
  jpa:
    hibernate:
      ddl-auto: update